def quadrado():
    print('+',  end=' ') 
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('+',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('+')
    print('|', end='         ')
    print('|', end='         ')
    print('|')
    print('|', end='         ')
    print('|', end='         ')
    print('|')
    print('+',  end=' ') 
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('+',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('+')
    print('|', end='         ')
    print('|', end='         ')
    print('|')
    print('|', end='         ')
    print('|', end='         ')
    print('|')
    print('+',  end=' ') 
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('+',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('-',  end=' ')
    print('+')
quadrado()